#!/bin/bash

PGNORIGINAL="[Event \"?\"]\\n[Site \"?\"]\\n[Date \"????.??.??\"]\\n[Round \"?\"]\\n[White \"?\"]\\n[Black \"?\"]\\n[Result \"*\"]\\n"

PGN="${PGNORIGINAL}\\n${1} *"


$(echo -e "$PGN" > temp.pgn)

pgn-extract/pgn-extract temp.pgn -Wuci

rm temp.pgn
